# Generated by Django 3.0.7 on 2020-06-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_category_location_photos_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='photos_image',
            field=models.ImageField(default='', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
