# Generated by Django 3.0.7 on 2020-06-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_photos_photos_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='photos_image',
            new_name='photo_image',
        ),
    ]
